### PR TITLE
Clean up logic of Io's constructor

### PR DESCRIPTION
**Pull request by szepeviktor**
This was so hard to do I cannot find a word for it in the dictionary :)

### CODE REVIEW

**Comment by szepeviktor** [comment]
Would this work??

```php
class Io
{
    public function __construct(protected mixed $value, public ?Result $result = null)
    {
        if ($value instanceof self) {
            $this->value = $value->value;
            $this->result ??= $value->result;
        }
    }
```

**Comment by otsch** [comment]
> Would this work??

Yes, I think that's perfect, like it! 👍🏻

Only one little thing, could you maybe please add a blank line between the lines assigning values to `$this->value` and `$this->result`? I've started to enforce this code style recently, you can read why here: https://twitter.com/chrolear/status/1503733220206170113 
Maybe it's not like this all over the whole repo yet, but I think in most places. Maybe I'll add it to the contribution guide 🤔

**Comment by szepeviktor** [comment]
> add a blank line between the lines assigning values

Done.

**Comment by szepeviktor** [comment]
> here: https://twitter.com/chrolear/status/1503733220206170113

String manipulation - even concatenation - is the job of low level libraries.
I strive not to touch string at all in general code.

**Pull request merged**
